### ISSUE TITLE
Исправления по сайту

### ISSUE THREAD

**Issue by jskonst** [ISUCT/UiEditor#3]
В пунктах меню (которые располагаются поверх "карусельки") следует уменьшить расстояние между символами. Сделать более сжатым (я забыл как этот интервал называется). Если все выглядит как на макете - сказать, я макет попрошу картинкой скинуть.

**Comment by TrefilovaNS** [comment]
Интервал между буквами-символами или между строчками разных ссылок в меню?

**Comment by jskonst** [comment]
В меню (вверху, например О Фонде, полет бабочки....) расстояние между символами одной строки большое. Возможно, просто Шрифт не такой как в макете и это оказывается важно :(. (Моя совсем не дизайнер.)
